### ISSUE TITLE
Add support for `aarch64`

### ISSUE THREAD

**Issue by thpani** [tudo-aqua/z3-turnkey#12]
On my Apple M1, `Z3Loader.loadZ3` throws because `aarch64` is not supported.

    java.lang.UnsatisfiedLinkError: Unsupported CPU architecture: aarch64
	at com.microsoft.z3.Z3Loader$CPUArchitecture.identify(Z3Loader.java:183)
	at com.microsoft.z3.Z3Loader.loadZ3(Z3Loader.java:57)
	at com.microsoft.z3.Native.<clinit>(Native.java:36)
	at io.github.tudoaqua.z3turnkey.Z3LoaderTest.testLoading(Z3LoaderTest.java:32)

Could you add support for this architecture?

As a workaround, is there a way to fall back onto unbundled / system Z3 binaries?

**Comment by no-preserve-root** [comment]
I'll look into it! Unfortunately, there are no official Z3 aarch64 binaries, so we might need to build them ourselves and/or implement a workaround…

**Comment by no-preserve-root** [comment]
Done! From 4.8.15 on, we ship self-built binaries for `aarch64` on MacOS. Note that the Maven `groupId` has been changed to `tools.aqua`.

**Comment by thpani** [comment]
This is great, thanks a lot!
