### ISSUE TITLE
DYLD_LIBRARY_PATH issue under macOS Catalina and BigSur

### ISSUE THREAD

**Issue by timosntr** [tudo-aqua/z3-turnkey#3]
I'm having an issue where the DYLD_LIBRARY_PATH is not set properly when installing z3-turnkey under macOS Catalina (10.15) and BigSur (11.0).

### Steps to reproduce:
```
git clone https://github.com/tudo-aqua/z3-turnkey.git
cd z3-turnkey
./gradlew assemble integrationTest
```
Executing this [JUnit Test](https://github.com/tudo-aqua/jconstraints-z3/blob/develop/src/test/java/gov/nasa/jpf/constraints/expressions/DoubleTest.java) via IntelliJ 2020.2.3

Which fails with 
```
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
```
(a more detailed stacktrace is below)

### "Solution" / Workaround:
Setting the DYLD_LIBRARY_PATH manually via an environment variable in the IDE.

---

Full stack trace:
```java
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.microsoft.z3.Native.<clinit>(Native.java:14)
	at com.microsoft.z3.Global.setParameter(Global.java:47)
	at gov.nasa.jpf.constraints.solvers.nativez3.NativeZ3Solver.<clinit>(NativeZ3Solver.java:55)
	at gov.nasa.jpf.constraints.solvers.nativez3.NativeZ3SolverProvider.createSolver(NativeZ3SolverProvider.java:59)
	at gov.nasa.jpf.constraints.solvers.nativez3.NativeZ3SolverProviderLegacy.createSolver(NativeZ3SolverProviderLegacy.java:37)
	at gov.nasa.jpf.constraints.solvers.ConstraintSolverFactory.createSolver(ConstraintSolverFactory.java:205)
	at gov.nasa.jpf.constraints.solvers.ConstraintSolverFactory.createSolver(ConstraintSolverFactory.java:220)
	at gov.nasa.jpf.constraints.solvers.ConstraintSolverFactory.createSolver(ConstraintSolverFactory.java:225)
	at gov.nasa.jpf.constraints.expressions.DoubleTest.expressionTest(DoubleTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by no-preserve-root** [comment]
@mmuesly can you look into that?

**Comment by mmuesly** [comment]
I added a test in #4. It works on my machine and so far, I could not reproduce the described bug. But I will work on it.

**Comment by no-preserve-root** [comment]
This looks like an IDE-specific classpath issue to me. The rewritten `com.microsoft.z3.Native.<clinit>` *does not call* `System.loadLibrary`, but `Z3Loader.loadZ3`. Apparently, the wrong version of Native.java is compiled by the IDE.

**Comment by mmuesly** [comment]
I think @no-preserve-root is right. I am working for a while with different builds and they work fine on big sure at the moment.
